MAIN_FEATURES = ["F_JS_SUSPICIOUS_HEAPSPRAY", "F_JS_RAWVALUE", "F_PDF_OPENACTION", "F_PDF_RENDITION", 
                "NUM_MISSING_PDF_OBJECTS", "F_C_JS_SCRIPTS_EXECUTION_FAILED", "F_C_JS_SCRIPTS_FOUND", 
                "F_C_JS_SCRIPTS_EXECUTED", "F_L_JS_SCRIPTS_LENGTH_TOTAL", "F_S_PERCENTAGE_SCRIPT",
                "C_UNESCAPE_CALLS", "C_UNESCAPE_LONG_PARAMS", "L_UNESCAPE_PARAM"]

print(sorted(MAIN_FEATURES))